## Make sure any changes doesn't break the functionality.

language : python
sudo : true
os : 
    - linux
  
python : 
  - "2.7"
  - "3.4"
  
addons:
    apt : 
        sources:
            -ubuntu-tool-chain-r-test  
  
before_install :
    - sudo apt-get install -y python-setuptools

branches:
    master
 
script : 
  - sudo python setup.py install
  - cd test
  - python test_package.py
